language: haskell

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.3

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y -qq cabal-install-1.20 ghc-$GHCVER alex
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
  - export PATH=~/.cabal/bin:$PATH # for alex
  - cabal update
  - sudo apt-get update
  - sudo apt-get install libstemmer-dev

install:
  - cabal sandbox init
  - cabal update
  - cabal install --only-dependencies

script:
  - cabal build
